### ISSUE TITLE
Download triggered by opening in New Tab

### ISSUE THREAD

**Issue by simpchristy** [MorbZ/no-pdf-download#1]
Hello,

If I right clink on a link and open in a new tab, the pdf is immediately downloaded instead of previewed. Is it possible to handle this condition as well? Unsure if this is beyond the scope of the add-on.

Thanks
Christy

**Comment by MorbZ** [comment]
In some cases the webserver is misconfigured and sends a wrong content-type header. In this case the addon has no way to tell that it's a PDF file beforehand and the file will be downloaded. If you post a link to the PDF I can check it.

**Comment by MorbZ** [comment]
For me the file is displayed correctly in the browser. And the server sends the correct headers. What browser and addon versions do you use?
