### ISSUE TITLE
"download" attribute foils Addons' functionality

### ISSUE THREAD

**Issue by Tabiskabis** [MorbZ/no-pdf-download#13]
I realize that fixing is probably beyond this addon's scope, but i still wanted to report a situation where its functionality is being broken.

simple example:
`<a href="example.pdf" download>i hate webdesigners who do this</a>`

smartass webdesigner example:
`<a href="generator.php?doc=example&dyn=some-data" download="example_some-data.pdf">death to pdf-forms</a>`

**Comment by jaens** [comment]
I'm unable to reproduce this attribute triggering a download (while this extension is enabled) in both Chrome (v95) and Firefox (v94).

**Comment by Tabiskabis** [comment]
Haven't encountered a situation like this since then. Will report more details if I run into one again.
Having looked at the addon's source, the download attribute can't have been the issue on that site.

**Comment by Tabiskabis** [comment]
There is also `Content-Dispositon: attachment; filename="something.pdf"`.  
Which, upon again inspecting the addon, seem to be handled already 🤷.

**Comment by jaens** [comment]
Yes. There _is_ some HTML attribute or JavaScript that can still trigger a download, but unfortunately I can't remember exactly what it was... 

In any case, it would require a content script to be injected into every page to handle it, which would require extending this add-on quite a bit (and passing extra Firefox add-on review for this...)
