### ISSUE TITLE
When printing out directly, printer doesn't handle text/math symbols correctly

### ISSUE THREAD

**Issue by FatMeowXD** [MorbZ/no-pdf-download#2]
Printer handles everything just fine when I open the file within a pdf reader/on other platforms, so it's not a printer/os issue.
I'm only having this problem within Firefox. 
This weird bug started out with math symbols being replaced with squares with four tiny distinguishable letters/numbers inside. Now it's affecting every other character(English plain text) as well. 
I'm assuming it could be a bug or a conflict with other plugins.

**Comment by MorbZ** [comment]
The addon does not change any of the content of PDFs or printing. Seems to be an encoding issue with the document. Maybe saving it and printing from the file may help.
