### ISSUE TITLE
Addon disabled with FF version upper v57

### ISSUE THREAD

**Issue by matt13000** [MorbZ/no-pdf-download#3]
Hi, I installed OpenKiosk 60.3 yesterday + your No PDF donwload add-on (which is a great one!). However, this morning, I'm not able to use it as OpenKiosk (specific FF version) says that this add-on is not secured and needs to be signed! And more on another computer I'm not able to install it as for the same error, FF displays "download failed, please check your connection". I followed a workaround, and modified the "xpinstall.signatures.required" option to False, and for the first computer it's ok, not for the second one, where I still can't install the addon.
Are you arleady working on a signed version?
Thank you for your help, your addon is just what I'm looking for my association...
Regards. Matt (from France)

**Comment by MorbZ** [comment]
There was a [huge bug](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/) in Firefox that caused all addons to be disabled. They did release an update by now, so updating Firefox may fix the issue.

**Comment by matt13000** [comment]
Hi MorbZ. As I use a specific FF version (openkiosk 60.3), there is no way to update it for the moment (I'm waiting for an update). Just to be sure, nobody warned you before for an issue about the unsigned add-on error message? Cause I don't understand why 2 PCs are ok (with the workaround) and 2 are not... thank you

**Comment by MorbZ** [comment]
I just checked it and the addon is approved and properly signed. I got no message from anybody else who has the problem. But as I wrote, there was a huge bug last saturday that caused all Firefox versions worldwide to reject addons because the certificate expired. I assume it may be the aftermath of the issue you encounter.

**Comment by matt13000** [comment]
OK thanks, I'll try again in few days. Thank you for your quick answer.
